apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "logto-chart.fullname" . }}-connectors
  labels:
    {{- include "logto-chart.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.connectors.schedule }}"
  suspend: {{ .Values.connectors.suspend }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: connectors
              persistentVolumeClaim:
                claimName: {{ include "logto-chart.fullname" . }}-connectors
            - name: dotnpm
              persistentVolumeClaim:
                claimName: {{ include "logto-chart.fullname" . }}-dotnpm
          containers:
          - name: {{ include "logto-chart.fullname" . }}-connectors
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command:
              - /bin/sh
              - -c
              - 'npm run cli connector add -- --official'
            volumeMounts:
              - name: connectors
                mountPath: /etc/logto/packages/core/connectors
                readOnly: false
              - name: dotnpm
                mountPath: /.npm
                readOnly: false
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
            securityContext:
              {{- toYaml .Values.securityContext | nindent 12 }}