{{- $fullName := include "logto-chart.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-db
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.db.user }}
  POSTGRES_PASSWORD: {{ .Values.db.password }}
  POSTGRES_DB: {{ .Values.db.database }}
  DB_URL: "postgresql://{{ .Values.db.user }}:{{ .Values.db.password }}@{{ $fullName }}-db:5432/{{ .Values.db.database}}"