apiVersion: v1
kind: Service
metadata:
  name: {{ include "logto-chart.fullname" . }}-db
  labels:
    app.kubernetes.io/component: database
    {{- include "logto-chart.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: database
    {{- include "logto-chart.labels" . | nindent 4 }}
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
    protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "logto-chart.fullname" . }}-db
  labels:
    app.kubernetes.io/component: database
    {{- include "logto-chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: database
      {{- include "logto-chart.labels" . | nindent 6 }}
  serviceName: {{ include "logto-chart.fullname" . }}-db
  template:
    metadata:
      labels:
        app.kubernetes.io/component: database
        {{- include "logto-chart.labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ include "logto-chart.fullname" . }}-db
        image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
        imagePullPolicy: {{ .Values.db.image.pullPolicy }}
        envFrom:
        - secretRef:
            name: {{ include "logto-chart.fullname" . }}-db
        ports:
        - name: postgresql
          containerPort: 5432
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - $PGUSER
            - -h
            - localhost
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: pgdata
    spec:
      accessModes:
        - ReadWriteOnce
      volumeMode: Filesystem
      resources:
        requests:
          storage: {{ .Values.db.storage }}